from ui.keyboard.layouts import (KeyboardLayout, LayoutKey, Modifier,
                                 general_keys)
from ui.keyboard.physical_layout import PhysicalLayout
from ui.keyboard.usb_hid import ScanCode

layout_en_us = KeyboardLayout(
    name="en-US",
    physical_layout=PhysicalLayout.ANSI,
    modifiers={
        ScanCode.LEFTSHIFT: Modifier.SHIFT,
        ScanCode.RIGHTSHIFT: Modifier.SHIFT,
    },
    keys={
        **general_keys,

        ScanCode.PRINT: LayoutKey("Print", is_character=False),
        ScanCode.SCROLLLOCK: LayoutKey("Scroll\nLock", is_character=False, representation="ScrollLock"),
        ScanCode.PAUSE: LayoutKey("Pause", is_character=False),
        ScanCode.GRAVE: LayoutKey("`", {Modifier.SHIFT: "~"}),
        ScanCode.ONE: LayoutKey("1", {Modifier.SHIFT: "!"}),
        ScanCode.TWO: LayoutKey("2", {Modifier.SHIFT: "@"}),
        ScanCode.THREE: LayoutKey("3", {Modifier.SHIFT: "#"}),
        ScanCode.FOUR: LayoutKey("4", {Modifier.SHIFT: "$"}),
        ScanCode.FIVE: LayoutKey("5", {Modifier.SHIFT: "%"}),
        ScanCode.SIX: LayoutKey("6", {Modifier.SHIFT: "^"}),
        ScanCode.SEVEN: LayoutKey("7", {Modifier.SHIFT: "&"}),
        ScanCode.EIGHT: LayoutKey("8", {Modifier.SHIFT: "*"}),
        ScanCode.NINE: LayoutKey("9", {Modifier.SHIFT: "("}),
        ScanCode.ZERO: LayoutKey("0", {Modifier.SHIFT: ")"}),
        ScanCode.MINUS: LayoutKey("-", {Modifier.SHIFT: "_"}),
        ScanCode.EQUAL: LayoutKey("=", {Modifier.SHIFT: "+"}),
        ScanCode.BACKSPACE: LayoutKey("⌫", is_character=False),
        ScanCode.TAB: LayoutKey("⇤\n⇥", is_character=False, representation="⇥"),
        ScanCode.Q: LayoutKey("q", {Modifier.SHIFT: "Q"}),
        ScanCode.W: LayoutKey("w", {Modifier.SHIFT: "W"}),
        ScanCode.E: LayoutKey("e", {Modifier.SHIFT: "E"}),
        ScanCode.R: LayoutKey("r", {Modifier.SHIFT: "R"}),
        ScanCode.T: LayoutKey("t", {Modifier.SHIFT: "T"}),
        ScanCode.Y: LayoutKey("y", {Modifier.SHIFT: "Y"}),
        ScanCode.U: LayoutKey("u", {Modifier.SHIFT: "U"}),
        ScanCode.I: LayoutKey("i", {Modifier.SHIFT: "I"}),
        ScanCode.O: LayoutKey("o", {Modifier.SHIFT: "O"}),
        ScanCode.P: LayoutKey("p", {Modifier.SHIFT: "P"}),
        ScanCode.LEFTBRACE: LayoutKey("[", {Modifier.SHIFT: "{"}),
        ScanCode.RIGHTBRACE: LayoutKey("]", {Modifier.SHIFT: "}"}),
        ScanCode.BACKSLASH_ANSI: LayoutKey("\\", {Modifier.SHIFT: "|"}),
        ScanCode.CAPSLOCK: LayoutKey("⇪", is_character=False),
        ScanCode.A: LayoutKey("a", {Modifier.SHIFT: "A"}),
        ScanCode.S: LayoutKey("s", {Modifier.SHIFT: "S"}),
        ScanCode.D: LayoutKey("d", {Modifier.SHIFT: "D"}),
        ScanCode.F: LayoutKey("f", {Modifier.SHIFT: "F"}),
        ScanCode.G: LayoutKey("g", {Modifier.SHIFT: "G"}),
        ScanCode.H: LayoutKey("h", {Modifier.SHIFT: "H"}),
        ScanCode.J: LayoutKey("j", {Modifier.SHIFT: "J"}),
        ScanCode.K: LayoutKey("k", {Modifier.SHIFT: "K"}),
        ScanCode.L: LayoutKey("l", {Modifier.SHIFT: "L"}),
        ScanCode.SEMICOLON: LayoutKey(";", {Modifier.SHIFT: ":"}),
        ScanCode.APOSTROPHE: LayoutKey("'", {Modifier.SHIFT: "\""}),
        ScanCode.ENTER: LayoutKey("↵"),
        ScanCode.LEFTSHIFT: LayoutKey("⇧", is_character=False),
        ScanCode.Z: LayoutKey("z", {Modifier.SHIFT: "Z"}),
        ScanCode.X: LayoutKey("x", {Modifier.SHIFT: "X"}),
        ScanCode.C: LayoutKey("c", {Modifier.SHIFT: "C"}),
        ScanCode.V: LayoutKey("v", {Modifier.SHIFT: "V"}),
        ScanCode.B: LayoutKey("b", {Modifier.SHIFT: "B"}),
        ScanCode.N: LayoutKey("n", {Modifier.SHIFT: "N"}),
        ScanCode.M: LayoutKey("m", {Modifier.SHIFT: "M"}),
        ScanCode.COMMA: LayoutKey(",", {Modifier.SHIFT: "<"}),
        ScanCode.DOT: LayoutKey(".", {Modifier.SHIFT: ">"}),
        ScanCode.SLASH: LayoutKey("/", {Modifier.SHIFT: "?"}),
        ScanCode.RIGHTSHIFT: LayoutKey("⇧", is_character=False, representation="RShift"),
        ScanCode.LEFTCTRL: LayoutKey("Ctrl", is_character=False, representation="LCtrl"),
        ScanCode.LEFTMETA: LayoutKey("Win", is_character=False, representation="LWin"),
        ScanCode.LEFTALT: LayoutKey("Alt", is_character=False, representation="LAlt"),
        ScanCode.SPACE: LayoutKey("␣", is_character=False),
        ScanCode.RIGHTALT: LayoutKey("Alt", is_character=False, representation="RAlt"),
        ScanCode.RIGHTMETA: LayoutKey("Win", is_character=False, representation="RWin"),
        ScanCode.PROPS: LayoutKey("Menu", is_character=False),
        ScanCode.RIGHTCTRL: LayoutKey("Ctrl", is_character=False, representation="RCtrl"),

        ScanCode.INSERT: LayoutKey("Ins", is_character=False),
        ScanCode.HOME: LayoutKey("Home", is_character=False),
        ScanCode.PAGEUP: LayoutKey("PgUp", is_character=False),
        ScanCode.DELETE: LayoutKey("Del", is_character=False),
        ScanCode.END: LayoutKey("End", is_character=False),
        ScanCode.PAGEDOWN: LayoutKey("PgDn", is_character=False),

        ScanCode.NUMLOCK: LayoutKey("Num\nLock", is_character=False, representation="NumLock"),
        ScanCode.KPSLASH: LayoutKey("/", representation="⊘"),
        ScanCode.KPASTERISK: LayoutKey("*", representation="⊛"),
        ScanCode.KPMINUS: LayoutKey("-", representation="⊖"),
        ScanCode.KP7: LayoutKey("7", {Modifier.NUMLK: "Home"}, representation="⑦"),
        ScanCode.KP8: LayoutKey("8", {Modifier.NUMLK: "↑"}, representation="⑧"),
        ScanCode.KP9: LayoutKey("9", {Modifier.NUMLK: "PgUp"}, representation="⑨"),
        ScanCode.KPPLUS: LayoutKey("+", representation="⊕"),
        ScanCode.KP4: LayoutKey("4", {Modifier.NUMLK: "←"}, representation="④"),
        ScanCode.KP5: LayoutKey("5", representation="⑤"),
        ScanCode.KP6: LayoutKey("6", {Modifier.NUMLK: "→"}, representation="⑥"),
        ScanCode.KP1: LayoutKey("1", {Modifier.NUMLK: "End"}, representation="①"),
        ScanCode.KP2: LayoutKey("2", {Modifier.NUMLK: "↓"}, representation="②"),
        ScanCode.KP3: LayoutKey("3", {Modifier.NUMLK: "PgDn"}, representation="③"),
        ScanCode.KPENTER: LayoutKey("Enter", representation="⏎"),
        ScanCode.KP0: LayoutKey("0", {Modifier.NUMLK: "Ins"}, representation="⓪"),
        ScanCode.KPDOT: LayoutKey(".", {Modifier.NUMLK: "Del"}, representation="⨀"),
    }
)
